name: Check version drift (preprod vs prod)

on:
  pull_request:
    branches: [release-prod]
    types: [opened, synchronize, reopened, edited]
  workflow_dispatch:

jobs:
  version-drift:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    env:
      PREPROD_PATH: preprod.json
      PROD_PATH: prod.json
      # Optionnel: exclure des services du contrôle (regex)
      IGNORE_REGEX: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compare preprod.json vs prod.json
        id: compare
        shell: bash
        run: |
          set -Eeuo pipefail

          PREPROD="$PREPROD_PATH"
          PROD="$PROD_PATH"

          HAS_DIFFS=0
          SUMMARY=$'### 🔎 Comparaison des versions (preprod vs prod)\n'

          if [[ ! -f "$PREPROD" || ! -f "$PROD" ]]; then
            SUMMARY+=$':warning: Fichiers introuvables: `'"$PREPROD"$'` ou `'"$PROD"$'`.\n'
            HAS_DIFFS=1
          else
            TMPDIR="$(mktemp -d)"
            trap 'rm -rf "$TMPDIR"' EXIT

            jq -r '.[].name' "$PREPROD" | sort -u > "$TMPDIR/preprod.names"
            jq -r '.[].name' "$PROD"     | sort -u > "$TMPDIR/prod.names"

            if [[ -n "${IGNORE_REGEX}" ]]; then
              grep -Ev "$IGNORE_REGEX" "$TMPDIR/preprod.names" > "$TMPDIR/preprod.filtered" || true
              grep -Ev "$IGNORE_REGEX" "$TMPDIR/prod.names"    > "$TMPDIR/prod.filtered"   || true
            else
              cp "$TMPDIR/preprod.names" "$TMPDIR/preprod.filtered"
              cp "$TMPDIR/prod.names"    "$TMPDIR/prod.filtered"
            fi

            MISSING_IN_PROD=$(comm -23 "$TMPDIR/preprod.filtered" "$TMPDIR/prod.filtered" || true)
            MISSING_IN_PREPROD=$(comm -13 "$TMPDIR/preprod.filtered" "$TMPDIR/prod.filtered" || true)
            COMMON=$(comm -12 "$TMPDIR/preprod.filtered" "$TMPDIR/prod.filtered" || true)

            if [[ -n "$MISSING_IN_PROD" ]]; then
              HAS_DIFFS=1
              SUMMARY+=$'\n**Manquants dans prod**
