name: Forward to main
on:
  push:
    branches: [ "release/*" ]  # à chaque push/merge sur une branche release

permissions:
  contents: write
  pull-requests: write

jobs:
  forward:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Open/Update PR to main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore: forward merge `${{ github.ref_name }}` → main"
          body: "Propagation automatique depuis `${{ github.ref_name }}`."
          base: main
          branch: auto/forward/${{ github.ref_name }}-to-main
          delete-branch: true
